---
- name: install nginx, mysql, php, git, vim, zsh
  hosts: dev-server
  # user: vagrant
  sudo : yes
  roles:
    - mysql
    - nginx
    - php55

    ## 予備roles
    # - apache # can't use with nginx
